<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.16</version>
        <relativePath/>
    </parent>

    <groupId>org.dragon.yunpeng</groupId>
    <artifactId>SpringBoot_Shibboleth_SAML_App1</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>SpringBoot_Shibboleth_SAML_App1</name>
    <description>Spring Boot SAML 2.0 Service Provider demo using Shibboleth as IdP</description>

    <properties>
        <java.version>21</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-saml2-service-provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        
        <!-- Explicit OpenSAML dependencies 
	    <dependency>
	        <groupId>org.opensaml</groupId>
	        <artifactId>opensaml-saml-api</artifactId>
	        <version>4.3.2</version>
	    </dependency>
	
	    <dependency>
	        <groupId>org.opensaml</groupId>
	        <artifactId>opensaml-saml-impl</artifactId>
	        <version>4.3.2</version>
	    </dependency>
	    -->
	    
    </dependencies>

    <build>
		<finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    
    <repositories>

	    <repository>
	        <id>shibboleth-releases</id>
	        <name>Shibboleth Releases</name>
	        <url>https://build.shibboleth.net/maven/releases/</url>
	    </repository>
	
	</repositories>
</project>
